---
resources:
  - name: op-github-repo
    type: git
    source:
      uri: https://github.com/minsohng/op-github.git
      branch: master

jobs:
  - name: op-github-e2e
    public: true
    plan:
      - get: op-github-repo
      - task: op-github-e2e
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: node, tag: latest }
          inputs:
            - name: op-github-repo
          run:
            path: op-github-repo/op-github-e2e.sh
          params:
            MAC_STADIUM_PASS: ((MAC_STADIUM_PASS))
            MAC_ADDRESS: ((MAC_ADDRESS))
            SSH_PRIVATE_KEY: ((SSH_PRIVATE_KEY))
